.github/actions/setup-go/action.yml
.github/workflows/ci.yml
.gitignore
.goreleaser.yml

Publishes the CLI via GitHub Actions - currently publishes to GitHub releases in this repository + Homebrew via https://github.com/depot/homebrew-tap.

Add publishing GitHub Actions workflows

---

pkg/cmd/build/build.go

Unless `--push` or `--output=...` is specified, default `depot build` to `--load` to load the resulting image into the local Docker context.

Default `depot build` to `--load`

---

pkg/builder/builder.go
pkg/cmd/build/build.go
pkg/cmd/build/buildx.go

By default the CLI will wait for the builder to become available, if desired `--no-wait` causes the CLI to exit with an error code if the builder is busy.

Add --no-wait option to exit if builder is busy

---

pkg/api/api.go
pkg/builder/builder.go
pkg/cmd/build/build.go
pkg/cmd/build/buildx.go

Uses new build API endpoints that track when a builder is ready. Also removes `--no-wait` as the new API no longer asks the CLI to wait to connect to a builder.

Use new build API endpoints, remove `--no-wait`

---

go.mod
pkg/api/api.go
pkg/api/context.go
pkg/builder/builder.go
pkg/builder/context.go
pkg/builder/proxy.go
pkg/buildxdriver/driver.go
pkg/buildxdriver/factory.go
pkg/cmd/build/buildx.go

Adds support for multi-platform builds (x86_64 and arm64) - the CLI will default to request the same platform as the host device, and Depot will provide a builder instance matching the requested architecture.

Support multi-platform builds

---

pkg/builder/builder.go

It's possible for the CLI to hang indefinitely when performing an initial builder connection check - this PR adds a timeout for that operation, plus one fix for a nil pointer error.

Fix nil pointer error, add timeout for connection checks

---

.github/workflows/ci.yml
Dockerfile

Previously all Docker images built with a `depot --version` set to `(devel)`. This PR sets the correct build flags for the Docker build.

Set build metadata when building Docker container

---

pkg/builder/builder.go

Second attempt at #22, but without `WithFailFast()`.

Set 5-second timeout on connection tests

---

.github/workflows/ci.yml
Dockerfile

The CLI Docker container does not yet have the correct version inside - this PR attempts to fix how `-ldflags` are passed to the build

Update ldflags in Docker build

---

pkg/cmd/build/build.go

This PR defaults `depot build` to leave the built image in the build cache (previously known as `--no-load`). Users should specify `--load` explicitly if they wish to download the resulting image locally.

Make --no-load the default behavior

---

pkg/api/api.go
pkg/cmd/build/buildx.go

If `depot build` returns an error, the CLI will report `{"status": "error"}` to the API, otherwise `{"status": "success"}`

Report build status to FinishBuild

---

pkg/api/api.go

One of our GET API requests was being sent with an empty JSON body (`{}`) - GET requests aren't allowed to send bodies, so this fixes that invalid request.

Fix sending body on GET request

---

cmd/depot/main.go
internal/update/update.go
pkg/api/api.go

Uses the new `dl.depot.dev` service to retrieve latest CLI version

Use `dl.depot.dev` to retrieve latest version information

---

go.mod
internal/build/build.go
pkg/cmd/build/build.go
pkg/cmd/build/dockerclient.go
pkg/cmd/version/version.go

Adds support for Docker's TLS environment variables (`DOCKER_TLS`, `DOCKER_TLS_VERIFY`, `DOCKER_CERT_PATH`) when loading images into the Docker daemon.

Add support for Docker TLS env vars

---

pkg/api/api.go
pkg/api/errors.go
pkg/buildxdriver/driver.go

Reports Depot API failure reasons to the Depot API, but omits sending the error message for BuildKit errors (to avoid sending any sensitive information about Dockerfile contents to the API).

Report Depot API failure reasons to API

---

pkg/api/request.go
pkg/api/rpc.go
pkg/builder/builder.go

Works around an issue where `User-Agent` can get overridden.

Send custom user-agent header

---

pkg/buildx/buildx.go
pkg/cmd/bake/bake.go
pkg/cmd/build/build.go
pkg/helpers/buildplatform.go

Allows forcing builds to run on Intel or Arm builders, regardless of the requested container platform, by specifying either `--build-platform` flag or the `DEPOT_BUILD_PLATFORM` environment variable. The valid build platform values are:
* `dynamic` - run on Intel or Arm builders depending on container platform, or both in the case of multi-platform builds (this is the default)
* `linux/amd64` - run only on Intel builders
* `linux/arm64` - run only on Arm builders

Add the ability to specify `--build-platform`

---

pkg/buildx/buildx.go

Reports build failures to the API, with reasons.

Report error messages on failure

---

pkg/buildxdriver/driver.go

Previously we only started the CLI's health check after acquiring a builder. This meant that if a builder was not acquired in 60s, the CLI would be incorrectly marked as disconnected.
Now this starts the health check first, so the CLI is able to wait for a builder as intended.

Start build health check early

---

go.mod
go.sum

Uses our BuildKit client version, with support for keep-alive configuration.

Use buildkit v0.11.3-depot.2 client

---

pkg/builder/builder.go

Previously if the gRPC health check stream was interrupted, health checks would stop entirely. Now they will restart the stream.

Allow health check to continue on temporary error

---

pkg/buildxdriver/driver.go

This change creates a persistent client instance inside each platform's driver. This allows health checks to check the same client that the build will use.

Use shared client inside buildx driver

---

pkg/buildx/commands/bake.go

This can cause bake to exit with status code 1 despite it not being a problem.

fix(bake): ignore spurious context canceled printer wait error

---

pkg/buildx/commands/build.go

It's not clear to me why it was not canceling correctly before, but this now mimics the previous code.

fix: allow graceful shutdown with context

---

pkg/buildx/commands/bake.go

Just like #77.  Still not clear to me why the we need a TODO rather than a normal context.

fix: allow graceful bake shutdown with context

---

.gitignore
cmd/depot/main.go
pkg/api/interceptors.go
pkg/api/request.go
pkg/ci/ci.go
pkg/ci/ci_test.go

We are trying to collect data about using CI or interactive terminal so we know what impacts future local builds will have on developer workflows.
Using environment variable heuristics from watson/ci-info we add "ci" or "terminal" to the user-agent string for outbound API requests.
We can detect the CI provider, so in the future we could also track that information; currently, we do not.

feat: determine CI provider via env var heuristics

---

pkg/helpers/token.go

We have confirmed this works in Buildkite and GitHub Actions, so it is safe to remove this and attempt an OIDC exchange if no token is passed in.

Remove `DEPOT_EXPERIMENTAL_OIDC`

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go

This works around the BuildKit `inconsistent graph state` error by retrying once. Existing build steps should remain cached, so this should resume the build at the point of error.

Retry BuildKit inconsistent graph state error

---

pkg/load/load.go
pkg/load/proxy.go

Occasionally, the randomly picked port would be rebound. This is a better solution as it has docker and the go network stack pick the random ports.

fix(load): have docker publish random port

---

pkg/load/cli.go
pkg/load/cli_test.go

Some projects may have characters that are not allowed as docker images. This now sanitizes the name appropriate for docker.

fix(load): sanitize project, build id, and bake target

---

pkg/load/registry.go

Sometimes we get the error "BLOB_UNKNOWN" but it is unclear if it is the manifest, the info, or the reading of data.

fix(load): differentiate between blob and manifest errors

---

pkg/buildx/build/build.go

On the server-side saving the build log becomes expensive as more builds are cached.
A permanent build log on the server has limited usefulness on depot's ephemeral architecture.
Previously, the server would save an entire copy of the provenance.
The optional provenance stored in the registry is unchanged.

perf: stop server-side build log recording

---

pkg/load/cli.go
pkg/load/registry.go

The internal logic in buildkitd requires a name before it will "unlazy," or download all layers.

fix(load): OCI image requires temporary name for buildkitd

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go
pkg/cmd/cache/reset.go
pkg/cmd/list/builds.go
pkg/helpers/project.go

When there is more than one dockerfile it could get tricky to
specify the location of the depot.json file.
This simplifies the approach by searching for the depot.json
starting from any specified bake or dockerfiles.
Signed-off-by: Chris Goller <goller@gmail.com>

feat: search for project from specified files or context

---

pkg/buildx/commands/bake.go

In large bake files with many images, the number of layer downloads can be overwhelming.
This restricts to run three concurrent pull requests. By default dockerd restricts the number of concurrent layers to download to three.  Thus, nine is our max number of concurrent layer downloads .

perf(load): limit the concurrency of bake image pulls

---

pkg/buildx/commands/build.go
pkg/load/load.go
pkg/load/registry.go

Image manifests and configs had a chance of being garbage collected by buildkit before they could be downloaded.  This race-condition could cause load errors.
We've changed buildkit's solve to return the manifests and configs and there should no longer be any race conditions.

fix(load): use manifest and config from build response

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go
pkg/load/image.go
pkg/load/load.go
pkg/load/proxy.go
pkg/load/pull.go
pkg/load/transport.go

When the docker daemon was remote, it could not always
reach the depot CLI registry.
In some environments like CircleCI the communication to a running
container was limited to just the docker API.
Docker attach provides a TCP connection that proxies a container's
STDIN and STDOUT.
This uses a serialized, framed packet format to receive blob requests
from the remote container's STDOUT and send blob responses to the
container's STDIN.
The protocol is binary and requires TTY to not be "true."
The framing protocol consists of a session id, data length, and data.
Regarding performance, it seems similar as before; sometimes slower
and sometimes faster.
Signed-off-by: Chris Goller <goller@gmail.com>

feat(load): use docker attach to proxy docker pull 

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go

The previous error is confusing, this updates it to mention that the cause is a `.dockerignore` file with invalid characters.

Rewrite exclude-patterns header to mention .dockerignore

---

pkg/buildx/commands/build.go

If a CI environment is detected, default to `--progress=plain` unless specified.

Default CI environments to plain progress printer

---

pkg/cmd/cache/reset.go

This PR contains two changes that affect the `pkg/cmd/cache` package:
1. remove duplicate `if projectID == ""` statement. for some reason there are two of it.
2. fix a panic error that occurs if the `depot cache reset` command executed **without arguments**. please see attached image for more details

fix: panic error on empty args when using depot cache reset command

---

install-cli.sh

Add `--no-location` for `curl` to retrieve release url, without this parameter, if there is `location` config in `~/.curlrc`, the value of `release_url` will be empty, which will make the install process fail.

Improve install-cli.sh robustness

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/lint.go
pkg/progress/progress.go

Linting issues that would fail the build was not previously reported.
One reason was that the terminal UX of vertex errors and status would print duplicate information.  This has been worked around with a new specialized printing function int he depot progress.
It'll end up looking something like this:

feat(lint): report failing linter issues to API

---

pkg/progress/progress.go

Lint would always print "linting failed" despite success.

fix(lint): remove spurious error message

---

pkg/dockerfile/upload.go

We saw significant traffic build context gRPC calls despite already reporting all content.  The calls contained empty bodies.
This now checks if there are any files to report before sending the request to the API.

fix: report build context only for unreported content

---

pkg/load/cli.go
pkg/load/load.go

Previously, manifests and configs were sent as annotations on the image index. This caused failures when pushing to GCR and oci-mediatypes was false.
Now a new export image option, `depot.export.image.version` has been added causing the builder service to return the manifests and configs in the solve response at the key `depot.export.image.version`.
This is backwards compatible for older builder services.

refactor(load): use manifests and configs from solve response

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go

This helps to push multiple platforms to gcr.io.

fix(load): default to depot manifest responses

---

pkg/buildx/build/depot.go
pkg/buildx/commands/bake.go

This fixes `bake --push` randomly not pushing.

Move `depot.export.image.version` to post-process function

---

.github/workflows/release.yml

Use ubuntu-latest-16-cores for release builds

---

pkg/buildx/commands/print.go

A different attempt at https://github.com/depot/cli/pull/145. This hides just the link from being printed if this environment variable is set.

Hide summary link if `DEPOT_NO_SUMMARY_LINK` is present

---

pkg/docker/dockerclient.go

Apparently I broke this when we upgraded Buildx versions. 🙂 
https://github.com/depot/cli/commit/d923252d9e1b4327d449a9e9d7b1be421987870c#diff-55142015445141572a329dfc967fa11ef225fa05ce94b3788417a46c9a84df4bL55-R55

Fix issue with Docker daemon TLS config

---

cmd/depot/buildx.go
cmd/depot/main.go
pkg/cmd/docker/docker.go
pkg/cmd/root/root.go

Adds a command that installs Depot as the primary Docker builder. Today that means:
1. Depot is installed as a Docker CLI plugin (`docker depot ...`)
2. The Depot plugin is set as the primary builder (`docker build ...` will call Depot)
3. Optionally, a shim buildx plugin is installed that routes `docker buildx build ...` to Depot
Once we have #148, we can add a "proper" buildx driver.

Add configure-docker command

---

pkg/load/pull.go

When running quiet printing mode, the error was
not checked for nil causing the image not not
be tagged correctly.
This bug would have created several spurious images 
that show up with temporary names such as
`localhost:32775/agahmfbenc:manifest`.

fix(load): tag images when running quiet mode

---

examples/build/main.go
pkg/buildxdriver/driver.go
pkg/machine/machine.go

Fixes an issue where the CLI would stop sending health pings to the API, causing builds to be cancelled.

Fix issue reporting build health

---

go.mod
go.sum
pkg/buildx/commands/build.go
pkg/cmd/docker/docker.go

docker compose has a race condition with docker buildx that causes more than one container with the same image name to be created.
This attempts to download the newest CLI container during the setup of the driver.
Once the upstream issue (buildx #2000) is released we can remove these extra steps.

feat(buildx): bootstrap driver by creating container

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go
pkg/sbom/sbom.go

The `--sbom-dir` will allow SBOMs to be saved into a directory.
We can use https://github.com/advanced-security/spdx-dependency-submission-action to upload SBOMs to github.

feat(sbom): add option to save sboms to directory

---

pkg/buildx/commands/build.go
pkg/load/load.go
pkg/sbom/sbom.go

When the image output or sbom is used we now output the manifest, config, and sbom into the metadata file.
I have example output below from running `depot build --output=type=image --metadata-file=metadata.json .`
metadata.json:
```json
{
"containerimage.buildinfo": {
"frontend": "dockerfile.v0",
"attrs": {
"filename": "Dockerfile",
"vcs:revision": "70daeb67cf219972a1123cd06d6c943944a3578f-dirty",
"vcs:source": "git@github.com:goller/nginx-pod-proxy.git"
},
"sources": [
{
"type": "docker-image",
"ref": "docker.io/library/ubuntu:18.04",
"pin": "sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98"
}
]
},
"containerimage.descriptor": {
"mediaType": "application/vnd.oci.image.index.v1+json",
"digest": "sha256:01654f77f087eb9527f14ec2a96f2ed0dbf438c72405cab8e5cd7ab131580bae" …
```

feat(metadata): output manifest, config, sbom in metadata file

---

go.mod
pkg/buildx/commands/bake.go
pkg/compose/compose.go

Loaded bake images use either the compose tags,
compose imageName, or the compose default name.
All of these naming schemes allow compose up
to use the depot baked images without needing
retagging.

feat(bake): output load names in compose format

---

go.mod
pkg/buildx/commands/bake.go
pkg/compose/compose.go

Previously, this would assume all files were compose files.

fix(bake): override tags only for compose files

---

pkg/buildx/commands/build.go

The error returned from buildkit was confusing.
This simplifies the error message to the useful
details.
Previous:
```
=> ERROR [5/5] COPY howdy /doody                                                                                     0.0s
------
> [5/5] COPY howdy /doody:
------
Error: failed to solve: failed to compute cache key: failed to calculate checksum of ref vv3yzwr47shug36z88iqkt7yq::l6be4rvphai7t4cl6oyb2j8mu: "/howdy": not found
```
Now:
```
=> ERROR [5/5] COPY howdy /doody                                                                                     0.0s
------
> [5/5] COPY howdy /doody:
------
Error:  "/howdy": not found. Please check if the files exist in the context.
```

feat: clarify missing file error message

---

cmd/depot/main.go
pkg/helpers/otel.go

Allows conditionally disabling the OTEL implementation by removing all OTEL env vars if `DEPOT_DISABLE_OTEL` is set.

Add DEPOT_DISABLE_OTEL env var support

---

pkg/cmd/push/push.go

This fixes an issue where project tokens were unable to `depot push`

Only attempt to resolve project list if build ID not specified

---

pkg/cmd/list/builds.go
pkg/cmd/list/projects.go

Addresses https://github.com/depot/cli/pull/232#issuecomment-1862467429.
We are currently overriding the `--output` when specified so if you do something like:
```shell
depot list project --output json | cat
```
You actually get a `csv` out even though you specified `json`.
This PR adds a check to see if `--output` has been specified before overriding it to `csv`.

Only override the output format for non terminals when --output isn't specified

---

go.mod
pkg/buildx/bake/bake.go
pkg/buildx/bake/compose.go
pkg/buildx/bake/hcl.go
pkg/buildx/bake/hclparser/body.go
pkg/buildx/bake/hclparser/expr.go
pkg/buildx/bake/hclparser/hclparser.go
pkg/buildx/bake/hclparser/stdlib.go
pkg/buildx/bake/remote.go
pkg/buildx/commands/bake.go
pkg/buildx/commands/print.go
pkg/compose/compose.go

This PR adds support for `matrix` and HCL `replace` in bake files by importing changes made in buildx 0.11.
For review, it's likely easiest to look at this commit, which is the changes made from buildx 0.10 to 0.11: https://github.com/depot/cli/commit/3f8bba27687332c771cc5769775e4b20f089c87b

Add support for new bake features (matrix, replace)

---

pkg/buildx/build/build.go

These previously didn't get reported

Capture and report errors when merging manifests

---

pkg/buildx/commands/bake.go

Overrides like `--set target.tags` apply before `compose.TargetTags(files)` is called, so we need to only set tags with generated tags if no other tags were resolved beforehand.

Allow tag overrides to apply to Compose files

---

pkg/cmd/buildctl/proxy.go
pkg/cmd/docker/docker.go

Buildx 0.13 no longer issues two `ListWorkers()` calls, so we need to be ready to start the builder after the first `ListWorkers()`

Fix buildkit proxy with buildx 0.13

---

cmd/depot/main.go
pkg/helpers/gha.go

Fixes the resolution of the GitHub Actions cache endpoint when running inside a Depot Actions runner.

Fix the resolution of GitHub Actions cache endpoint

---

pkg/cmd/pull/options.go
pkg/load/cli.go
pkg/load/pull.go

This is needed when pulling into the containerd content store, as containerd will assume Docker Hub as the server unless an address is specified.

Fix auth ServerAddress for containerd content store

---

pkg/buildx/build/build.go
pkg/progress/log.go

Getting ignored git files can take significant amount of time. This now logs the start and end times of git checks.

feat: log when getting git provenance

---

pkg/build/build.go
pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go
pkg/helpers/build.go
pkg/load/cli.go

The UseLocalRegistry feature flag is always true, and we don't do anything with ProxyImage returned from the API

Remove unused ProxyImage and UseLocalRegistry fields

---

README.md
pkg/buildx/bake/bake.go
pkg/buildx/bake/compose.go
pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go
pkg/buildx/commands/lint.go
pkg/progresshelper/shared.go

Adding x-depot to compose files allows different services to be built on different projects.  This allows faster concurrent builds.

feat(bake): allow concurrent projects with x-depot bake extension

---

pkg/cmd/pull/options.go

This changes `pull` so that `depot pull --target abc --tag hello-world ...` will tag the pulled image as exactly `hello-world` - currently it would get tagged with `hello-world-TARGETNAME` even though only one image is being pulled.
Pull should still add the `-TARGETNAME` suffix to the image if multiple targets are being pulled with a user-specified tag.

Only add `-target` suffix to user tags if pulling multiple targets

---

pkg/load/pull.go

If body responses from the docker daemon were not read fast enough, docker would block image pulls.
This now reads the messages from the docker response body and no longer blocks.
As a bonus, context is now respected so ctrl+c will stop an image pull.
part of DEP-1801

refactor: do not block reading messages from docker daemon

---

pkg/helpers/gha.go

Restores the upstream Actions cache URL if present.

Fix GHA cache URL in Depot runners

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go
pkg/cmd/bake/bake.go
pkg/cmd/build/build.go
pkg/cmd/docker/docker.go
pkg/cmd/exec/exec.go
pkg/cmd/pull/pull.go
pkg/cmd/pulltoken/pulltoken.go
pkg/cmd/push/push.go
pkg/cmd/root/root.go
pkg/dockerclient/client.go

Some tools like AWS CDK call the Depot build command like `depot --config /tmp/configXXXXX build ...` intending to set the path to Docker config. This PR adds a hidden CLI flag to accept this input and set the `DOCKER_CONFIG` environment variable to the provided value.

Allow specifying `DOCKER_CONFIG` via `--config`

---

pkg/cmd/push/blobs.go
pkg/cmd/push/push.go

Right now any non-2xx status code encountered when running `depot push` aborts the entire push. This PR changes this so that any 5xx status code is retried up to 3 times with a 5-second sleep in between each attempt. This should work around temporary unavailability upstream (e.g. the Cloudflare 524 error code).

Retry `depot push` on 5xx errors

---

Makefile
pkg/cmd/docker/docker.go
pkg/load/proxy.go

We have seen some GHCR outages that cause the CLI to be unable to pull its helper container. This PR switches from GHCR to ECR Public for improved stability.

Pull CLI helper image from ECR Public

---

pkg/build/build.go
pkg/helpers/build.go

We don't need to call `GetBuild` on the default path that already called `CreateBuild`.

Fix handling of default build create path

---

pkg/cmd/docker/docker.go
pkg/retry/retry.go

This should try to bootstrap the buildx driver container up to three times before erroring

Retry bootstrapping failures

---

README.md
pkg/cmd/gocache/gocache.go
pkg/cmd/gocache/wire/wire.go
pkg/cmd/root/root.go

Set `GOCACHEPROG="depot gocache"` to cache Go tool cache remotely in depot.
This supports Go version 1.24 or greater.

feat: support remote cache for Go compiler

---

README.md
pkg/cmd/gocache/gocache.go

Writing the GOCACHEPROG to GOCACHE allows
us to use the existing go tooling for cache.
To clean the cache run `go clean -cache`

refactor: write GOCACHEPROG cache into GOCACHE

---

go.mod
pkg/buildx/bake/buildflags/cache.go
pkg/buildx/build/build.go
pkg/helpers/gha.go

Upstream has moved various type to string conversions to a variety of different places in the code.

fix: add SBOM and S3 caching secrets

---

go.mod
pkg/buildx/bake/buildflags/cache.go
pkg/buildx/build/build.go
pkg/helpers/gha.go

Revert "fix: add SBOM and S3 caching secrets"

---

pkg/oidc/actionspublic/exchange.go
pkg/oidc/actionspublic/types.go

Possibly a fix for an issue with the OIDC exchange.

Pass GitHub run attempt ID to OIDC exchange

---

README.md
pkg/cmd/pull/pull.go
pkg/cmd/pulltoken/pulltoken.go
pkg/cmd/push/manifests.go
pkg/cmd/push/push.go

the registry is no longer ephemeral, as you can store images for any
length of time. removing references to the registry being 'ephemeral'
makes sense.

docs: remove references to 'ephemeral' registry

---

pkg/cmd/gocache/gocache.go

Go 1.23 would send `ObjectID`.
Previously, the code would panic because it sliced into an empty Go 1.24 `OutputID` field. Now, we correctly guard and set the outputID.

fix(gocacheprog): support go 1.23

---

Dockerfile
pkg/cmd/buildctl/proxy.go

Pulumi / modern buildx is calling the Info method, which currently shuts down the buildx proxy. This PR removes that shutdown, plus leaves a disabled debugging logger in place for next time we need to debug this.

Fix pulumi / buildx

---

pkg/load/cli.go

When specifying registry pull options for loading from the registry, if platform is specified for the target, specify platform in pull options to be used when pulling from the registry. If there are multiple platforms configured for the target, we don't specify a platform. Alternatively this can be updated to use the first platform if that makes more sense than not specifying one.

fix: specify platform for registry pull when load using registry

---

README.md
pkg/cmd/push/auth.go

Pushing to registries previously depended on the default docker method of reading the docker config file for auth tokens.
This was inconvenient because the format is complicated and is shared among all concurrent depot pushes.
To support more concurrency with ephemeral tokens, we've introduced the environment variables
`DEPOT_PUSH_REGISTRY_USERNAME` and `DEPOT_PUSH_REGISTRY_PASSWORD`.
To use with depot push:
```
DEPOT_PUSH_REGISTRY_USERNAME=AWS DEPOT_PUSH_REGISTRY_PASSWORD=hunter2 depot push ...
```

feat: support depot push w/o docker .config credentials

---

pkg/cmd/cargo/cargo.go
pkg/cmd/root/root.go

Adds a wrapper around `cargo` that configures Depot Cache.

Add `depot cargo` command

---

pkg/cmd/cargo/cargo.go

This makes the `depot cargo` respect the `DEPOT_CACHE_TOKEN` env var in our Actions runners

Read DEPOT_CACHE_TOKEN from environment

---

pkg/cmd/cargo/cargo.go
pkg/cmd/gocache/gocache.go
pkg/helpers/token.go

Various depot commands (e.g. `depot claude`, `depot cargo`) would benefit from default auth mechanisms within Depot execution environments. This PR adds support for a `DEPOT_JIT_TOKEN` and a legacy `DEPOT_CACHE_TOKEN` present in such environments.

feat: support JIT tokens from Depot environments

---

pkg/buildx/commands/build.go

This implements support for the `depot build --annotation` flag, to add additional annotations to the build.

Add support for `--annotation` flag

---

pkg/buildx/commands/bake.go

Currently when using `depot bake` with multiple project IDs, we are calling `build.Finish()` when the entire `BakeCmd()` function returns, which means that all sub-builds for each of the participating projects wait to be marked as done until every build is done.
This PR moves the `build.Finish()` into the sub-build goroutine, so that builds are able to complete as soon as they are actually done, without waiting on each other.

Finish multi-project bake builds when complete

---

pkg/buildx/commands/bake.go
pkg/buildx/commands/build.go
pkg/registry/cli.go

- Fixed metadata file target handling by removing unused `targets` parameter from `writeMetadataFile` function
- Updated target list to be derived from actual metadata keys using `maps.Keys(metadata)`
- Ensures targets in metadata file accurately reflect the actual build results

fix: correct metadata file target handling by deriving from actual metadata keys
