cmd/depot/main.go, internal/build/build.go, pkg/cmd/root/root.go, pkg/cmd/version/version.go
Adds build date to `depot --version` and `depot version`
=> Add build date to version

pkg/builder/builder.go
* Fixes formatting for log messages printed during builder startup / connection
* Increases the timeout for busy builders to 30 minutes. It's possible we want to default to having no timeout at all, or add a user-configurable one, because we're waiting effectively for the user's existing build to complete, which has a variable / unknown runtime
=> Adjust builder waiting logs, increase timeout to 30 minutes

pkg/api/api.go, pkg/api/auth.go, pkg/api/errors.go
Attempts to decode API error responses and prints the returned error message
=> Print API error messages

.goreleaser.yml, cmd/depot/main.go, go.mod, go.sum, internal/update/update.go, pkg/api/api.go, pkg/api/request.go, pkg/config/config.go
Once per hour, checks to see if the current version of the CLI is out of date
=> Add CLI update notice

.github/workflows/ci.yml, Dockerfile
Builds a Docker container for the CLI
=> Build Docker container for CLI

pkg/api/request.go
* Send a user agent with all API requests
* Display info or warning messages from the API server if provided
=> API HTTP client cleanups

pkg/builder/builder.go
=> Revert "Fix nil pointer error, add timeout for connection checks"

pkg/api/api.go
This API is unused, cleaning up 🧹
=> Remove unused API method handler

pkg/builder/builder.go
We have seen some spurious network issues cause the CLI to be unable to acquire a builder connection within the timeout.
Before making any more involved changes, this PR adds one retry phase, so if the first attempt to acquire a builder fails, it is retried once before being reported as an error. So that the CLI doesn't wait any longer than it does currently, the timeout for acquiring a connection is now 30 seconds rather than 60, so the retry will happen half-way through the previous window.
=> Retry acquiring builder if the first attempt results in an error

pkg/buildxdriver/driver.go
Makes two changes to enable faster connection to builder machines:
* Checks builder status once per second, for 120 seconds. Previously it used a backoff algorithm that would effectively ensure ~20 seconds of waiting time for machines that needed to boot.
* Directly dial the machine with `net.Dial`, which is faster than buildkit's internals
=> Support faster connections to builders

pkg/buildx/buildx.go, pkg/cmd/bake/bake.go
This allows the CLI to receive a build ID via an environment variable, if a build was created externally (e.g. via the upcoming Depot API).
=> Allow passing existing build ID via env var

pkg/buildx/commands/progress.go
It is distracting and causing undo noise if there are issues reporting build timings to the API.
It is totally fine if we miss a few build timings.
=> refactor(build): ignore any errors reporting timings

pkg/buildx/commands/build.go
=> Retry BuildKit error failed to get state for index

pkg/load/proxy.go
Downloading the proxy image could take quite some time (20 seconds) if pulling from large concurrent bake jobs.
Now, the proxy image will only be pulled once per depot run. Additionally, if the proxy image already exists, the pull will be skipped altogether.
=> perf(load): skip proxy pull if exists or download once

pkg/load/registry.go
Report when CLI is not able to fetch a manifest from the server.
=> Report manifest errors to Sentry

pkg/buildx/commands/build.go
Retrying when dockerfile or context come from stdin causes failures as we cannot re-read the data.
This skips retrying and fails the build.
=> feat(load): skip retry if inputs are from stdin

pkg/buildx/build/build.go
To determine if the buildkit server supported S3 and gha caching, an entire build cycle was used simply to run "ping."
The build ran five gRPC requests of `ListWorkers`, `Status`, `Session`, `Solve`, and `Ping`.
Ultimately, it was the `Ping` that matters as it returns the capabilities of the server.
Of the dozens of capabilities the client looks two for caching (s3 and gha) and attestations.
Depot supports those three and thus we can remove this entire cycle.
Incidentally, this first build happens to start a garbage collection that runs during the real second build.
=> perf: remove extra build used for capability discovery

pkg/load/load.go, pkg/load/proxy.go, pkg/load/transport.go
Heavily loaded machines may be slow to start the HTTP registry server. Now, we wait to receive the version over STDERR before instructing docker to pull the image.
The current wait-time is up to 10 seconds; if we do not receive the version number before that time, we try to pull anyway with failures causing our standard use of docker tar load.
This is also sorta backwards compatible: if one used an older proxy container it would work but take an extra 10 seconds.
=> feat(load): wait for proxy ready signal before pull

README.md
=> Also add Linux installation steps in README.md

README.md, pkg/cmd/logout/logout.go, pkg/cmd/root/root.go
Adds a `logout` command to mirror `login`
=> Add logout command

cmd/depot/main.go, pkg/cmd/docker/docker.go, pkg/cmd/root/root.go
Currently behind a `depot docker install` hidden subcommand.
=> Implement Docker CLI plugin interface

pkg/buildx/commands/bake.go, pkg/buildx/commands/build.go
=> Print build URL at start

cmd/depot/main.go
Adds `bake` to the list of shim subcommands
=> Add shim for `buildx bake`

README.md, pkg/cmd/docker/docker.go
Removing until we implement a buildx driver
=> Unpublish buildx-shim

npm/packages/cli/README.md
=> npm: update README

pkg/sbom/sbom.go
Simplify using slices rather than maps.
=> refactor(sbom): use flattened SBOM structure

pkg/cmd/docker/docker.go
Previously, buildx would fail if extra files are in the `.docker/instances` directory.  This could happen if the program were to stop before the instance configuration file was completely written leaving behind a temporary file.
This rewrites dockers's ioutils.AtomicWriteFile to create the temporary file in the TempDir avoiding the problem.
=> fix(buildx): use TempDir for configuration atomic writes

pkg/buildx/commands/bake.go
For https://github.com/depot/bake-action/issues/23
=> Strip cwd:// prefix from incoming files

pkg/oidc/actionspublic/exchange.go
Adds missing newline, prints to stderr.
=> Update public OIDC challenge message

pkg/buildx/commands/bake.go, pkg/buildx/commands/build.go
Sends the progress of `--load` to the UI for display.
=> Report `--load` progress to UI

pkg/buildx/commands/bake.go
Previously, on retry-able errors the shared printer would write to a closed channel because the reference count was decremented on any error.
Now, the reference count is decremented only when the error is fatal.
=> fix(bake): only close progress after error retries

pkg/cmd/gocache/gocache.go
In a CI workflow it is pretty common for the go-cache to be saved and restored.
Thus, we skip writing a put cache request to disk if it already exists.
=> perf: skip gocache disk put if file already exists

pkg/cmd/claude/remote.go, pkg/cmd/claude/secrets.go
Addresses new cases added by #375
=> fix: use new helper functions

pkg/cmd/claude/remote.go
Updates the log message printed when a sandbox is started:
```
✓ Claude sandbox started!
Session ID: fe3c3902-f437-4e8a-b2d3-f613aaa895ab
Link: https://depot.dev/orgs/ORGID/claude/fe3c3902-f437-4e8a-b2d3-f613aaa895ab
```
=> Update log messages for sandbox links

pkg/cmd/claude/claude.go
This was unintentionally disabled, fixing...
=> Update auto-detection of claude repo
